spring:
  application:
    name: manager-api
  datasource:
    url: jdbc:h2:file:./staging-area/h2/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    consumer:
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      group-id: manager-api
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #TODO fix this later
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'


server:
  port: 9999

kafka:
  file-events-topic: file-watcher-events
  bootstrap-servers: localhost:9092
  file-record-events-topic: file-record-events
  file-request-status-updates-topic: file-request-status-updates

file-records-delta-table-location: "/Users/srirajkadimisetty/projects/demos/e2e-prototype/approach-1/staging-area/deltalake_storage/file_records"
base-staging-area: "/Users/srirajkadimisetty/projects/demos/e2e-prototype/approach-1/staging-area"
spark-properties:
  file-splitter:
    sparkSubmitPath: /Users/srirajkadimisetty/tools/spark-3.5.1-bin-hadoop3-scala2.13/bin/spark-submit
    jarPath: /Users/srirajkadimisetty/projects/demos/e2e-prototype/approach-1/spark-process/target/spark-process-0.0.1-SNAPSHOT.jar
    mainClass: com.example.ReadAndSplitFileRequest
    master: local[2]
    logFileAppBaseLocation: /Users/srirajkadimisetty/projects/demos/e2e-prototype/approach-1/staging-area/logs/
    appType: ReadAndSplitFileRequest
    configFileStagingLocation: /Users/srirajkadimisetty/projects/demos/e2e-prototype/approach-1/staging-area/fileSplitJob
  output-file-writer:
    sparkSubmitPath: /Users/srirajkadimisetty/tools/spark-3.5.1-bin-hadoop3-scala2.13/bin/spark-submit
    jarPath: /Users/srirajkadimisetty/projects/demos/e2e-prototype/approach-1/spark-process/target/spark-process-0.0.1-SNAPSHOT.jar
    mainClass: com.example.SparkOutputFileWriter
    master: local[2]
    logFileAppBaseLocation: /Users/srirajkadimisetty/projects/demos/e2e-prototype/approach-1/staging-area/logs/
    appType: SparkOutputFileWriter
    configFileStagingLocation: /Users/srirajkadimisetty/projects/demos/e2e-prototype/approach-1/staging-area/sparkOutputFileWriter

springdoc:
  api-docs:
    enabled: true
    #Default : http://localhost:9999/api-docs
    path: /swagger-docs
  swagger-ui:
    #Default : http://localhost:9999/swagger-ui/index.html
    path: "/swagger-ui.html"